title: Kian Cho
description: Hello, I am Kian (he/him). I am a category theory enjoyer, a rhythm game enthusiast, a stack of cats in trench coat, or a terrible goose.
logo: assets/portrait.png
baseurl: ""
